plugins {
    id 'com.android.application'
}

android {
    namespace 'br.com.listadecompras'
    compileSdk 34

    defaultConfig {
        applicationId "br.com.listadecompras"
        minSdk 26
        targetSdk 34
        versionCode 3
        versionName "1.2"
    }

    signingConfigs {
        debug {
            storeFile file('lista-keystore.jks')
            storePassword 'listadecompras'
            keyAlias 'lista'
            keyPassword 'listadecompras'
        }
    }

    buildTypes {
        debug {
            signingConfig signingConfigs.debug
        }
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
